user:
  name: nifi

install:
  version: 1.9.2
  source: salt://{{ slspath }}/files/

config:
  mem_size: {{ grains['mem_total'] }}/2
  http_port: 80

disk:
  enabled: False
  mount_point: /mnt

cluster:
  enabled: False